#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright (c) 2026 The bare-swift Project Authors.
#
# Reads the Brotli static dictionary binary (122784 bytes) and writes
# Sources/Brotli/Dictionary.swift with the bytes embedded as a `static
# let bytes: [UInt8] = [ ... ]` array literal. The offsets and counts
# per word-length are baked from RFC 7932 § 8.
#
# Usage:
#   python3 scripts/generate_dictionary.py [input.bin] [output.swift]
# Defaults: /tmp/brotli-dictionary.bin and Sources/Brotli/Dictionary.swift.
import sys
import pathlib

src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/brotli-dictionary.bin")
out = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "Sources/Brotli/Dictionary.swift")
data = src.read_bytes()
assert len(data) == 122784, f"expected 122784 bytes, got {len(data)}"

with out.open("w") as f:
    f.write("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception\n")
    f.write("// Copyright (c) 2026 The bare-swift Project Authors.\n")
    f.write("//\n")
    f.write("// This file is auto-generated by scripts/generate_dictionary.py from\n")
    f.write("// https://github.com/google/brotli/blob/master/c/common/dictionary.bin\n")
    f.write("// (MIT-licensed; see NOTICE).\n")
    f.write("//\n")
    f.write("// Source SHA-256: 20e42eb1b511c21806d4d227d07e5dd06877d8ce7b3a817f378f313653f35c70\n\n")
    f.write("/// The 122784-byte Brotli static dictionary from RFC 7932 Appendix A.\n")
    f.write("///\n")
    f.write("/// Words are indexed by length (4..24). For word-length `L`, the\n")
    f.write("/// dictionary contains `counts[L]` words, each `L` bytes, packed\n")
    f.write("/// contiguously starting at `bytes[offsets[L]]`.\n")
    f.write("enum Dictionary {\n")
    f.write("    /// Byte offset within `bytes` for each word-length 0..24.\n")
    f.write("    /// Lengths 0..3 are unused (Brotli dictionary words start at\n")
    f.write("    /// length 4); offsets for those indices are 0.\n")
    f.write("    static let offsets: [Int] = [\n")
    f.write("        0, 0, 0, 0, 0, 4096, 9216, 21504, 35840, 44032, 53248,\n")
    f.write("        63488, 74752, 87040, 93696, 100864, 104704, 106752,\n")
    f.write("        108928, 113536, 115968, 118528, 119872, 121280, 122016,\n")
    f.write("    ]\n\n")
    f.write("    /// Number of words at each length (index by length 0..24).\n")
    f.write("    /// Length 0..3 are unused.\n")
    f.write("    static let counts: [Int] = [\n")
    f.write("        0, 0, 0, 0, 1024, 1024, 1024, 1024, 2048, 2048,\n")
    f.write("        2048, 2048, 2048, 2048, 1024, 1024, 1024, 1024,\n")
    f.write("        1024, 512, 512, 512, 512, 512, 512,\n")
    f.write("    ]\n\n")
    f.write("    static let bytes: [UInt8] = [\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    f.write("    ]\n")
    f.write("}\n")

print(f"Wrote {out} ({len(data)} bytes embedded)")
